name: Build 

on: [push]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: set up go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20

      - name: display go version
        run: go version

      - name: GITHUB_REF
        run: echo ${GITHUB_REF##*/}
      - name: run
        run: make run


      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            {
              "text": "GitHub Action indexvm  result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}\n \n",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "GitHub Action indexvm  result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}\n \n"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
